name: run unit tests of feature branches

on: 
  push:
  schedule:
    - cron: '0 23 * * *'


jobs: 
  nighly_build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: Run Unit Tests
          run: mvn test

        - name: Run Build Maven
          run: mvn -DskipTests - package --no-transfer-progress --file ./pom.xml

        - uses: actions/upload-artifact@master
          with:
             name: digibank.war
             path: ./target/*blankfactor*.war
