name: Run unit test of feature BlankFactor

on: 
  push:

jobs: 
  blankfactor_Tests:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: Run Unit Tests
          run: mvn test

        - name: Run Build Maven
          run: mvn -DskipTests package -no-transfer-progress --file ./pom.xml

        - uses: actions/upload-artifact@v4
          with:
             name: blankfactor.war
             path: target/*blankfactor*.war
